// Regenerates src/pdf/fonts.generated.ts: Inter (SIL OFL) latin + latin-ext + cyrillic as inline @font-face CSS,
// so PDF rendering never depends on fetching fonts over the network.
// Usage: node scripts/build-fonts.mjs <dir with inter.css.tpl and inter-<subset>.woff2>
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2];
const css = readFileSync(join(dir, "inter.css.tpl"), "utf8").replace(
  /__([a-z-]+)__/g,
  (_, subset) => `data:font/woff2;base64,${readFileSync(join(dir, `inter-${subset}.woff2`)).toString("base64")}`,
);
writeFileSync(
  new URL("../src/pdf/fonts.generated.ts", import.meta.url),
  `// Generated by scripts/build-fonts.mjs. Inter font, SIL Open Font License 1.1.\nexport const FONT_CSS = ${JSON.stringify(css)};\n`,
);
